### ISSUE TITLE
Error after ng serve

### ISSUE THREAD

**Issue by Jorg71** [aaronksaunders/afwithngcli#1]
OS: Windows 10.

I just downloaded the files. After "ng serve" I get the following errors:

```
c:\Users\jh\Projects\afwithngcli>ng serve
Could not require 'angular-cli-build.js': Cannot find module 'angular-cli/lib/broccoli/angular2-app'
Error: Could not require 'angular-cli-build.js': Cannot find module 'angular-cli/lib/broccoli/angular2-app'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (c:\Users\jh\Projects\afwithngcli\angular-cli-build.js:7:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

Could you please give me a hint to solve this? I'm new.

**Comment by aaronksaunders** [comment]
if you are upgrading angular-cli... you need to complete remove the old
version, clear your cache and do a new install

## 

Aaron K. Saunders
CEO Clearly Innovative Inc.
aaron@clearlyinnovative.com
www.clearlyinnovative.com
@aaronksaunders

This email message and any attachment(s) are for the sole use of the
intended recipient(s) and may contain proprietary and/or confidential
information which may be privileged or otherwise protected from disclosure.
Any unauthorized review, use, disclosure or distribution is prohibited. If
you are not the intended recipient(s), please contact the sender by reply
email and destroy the original message and any copies of the message as
well as any attachment(s) to the original message.

**Comment by Jorg71** [comment]
I removed the cli, cleared the cache and installed new:

```
npm uninstall -g angular-cli
npm cache clean
npm install -g angular-cli
```

Actual versions:
OS: Windows 10
NPM version: 3.10.5
Node version: v4.4.7
angular-cli version: 1.0.0-beta.10

Then I cloned the files (with git bash in administrator mode):

`git clone https://github.com/aaronksaunders/afwithngcli.git`

Move into the project folder:

`cd afwithngcli`

After that ng serve:

```
$ ng serve
The Broccoli Plugin: [Funnel] failed with:
Error: Attempting to watch missing directory: typings
    at EventEmitter.Watcher_addWatchDir [as addWatchDir] (C:\Users\jh\node_modules\angular-cli\node_modules\broccoli-sane-watcher\index.js:90:11)
    at C:\Users\jh\node_modules\angular-cli\node_modules\angular-cli-broccoli\lib\builder.js:95:35
    at lib$rsvp$$internal$$tryCatch (C:\Users\jh\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\Users\jh\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at C:\Users\jh\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:331:11
    at lib$rsvp$asap$$flush (C:\Users\jh\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

The broccoli plugin was instantiated at:
    at Funnel.Plugin (C:\Users\jh\node_modules\angular-cli\node_modules\broccoli-plugin\index.js:10:31)
    at new Funnel (C:\Users\jh\node_modules\angular-cli\node_modules\broccoli-funnel\index.js:44:10)
    at Angular2App._buildInputTree (C:\Users\jh\node_modules\angular-cli\lib\broccoli\angular2-app.js:93:7)
    at new Angular2App (C:\Users\jh\node_modules\angular-cli\lib\broccoli\angular2-app.js:51:41)
    at module.exports (C:\Users\jh\projects\afwithngcli\angular-cli-build.js:10:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (C:\Users\jh\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:55:19)
    at Class.module.exports.Task.extend.init (C:\Users\jh\node_modules\angular-cli\node_modules\angular-cli\lib\models\builder.js:89:10)
    at new Class (C:\Users\jh\node_modules\angular-cli\node_modules\core-object\core-object.js:18:12)
    at Class.module.exports.Task.extend.run (C:\Users\jh\node_modules\angular-cli\node_modules\angular-cli\lib\tasks\serve.js:15:19)
    at C:\Users\jh\node_modules\angular-cli\node_modules\angular-cli\lib\commands\serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (C:\Users\jh\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (C:\Users\jh\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (C:\Users\jh\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (C:\Users\jh\node_modules\angular-cli\node_modules\rsvp\dist\rsvp.js:1198:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)


Livereload server on http://localhost:49152
Serving on http://localhost:4200/
```

Did I do wrong? I'm not sure.

**Comment by rogerbernardi** [comment]
Hi! Try this...

`npm uninstall -g angular-cli
`
`npm cache clean`
`npm install -g angular-cli`
`git clone https://github.com/aaronksaunders/afwithngcli.git`
`cd afwithngcli`
`npm install`
Edit file main.ts locate at  afwithngcli/src/mais.ts

```
//start of main.ts
import { bootstrap } from '@angular/platform-browser-dynamic';
import { enableProdMode } from '@angular/core';
import { AppComponent, environment } from './app/';
import { FIREBASE_PROVIDERS, defaultFirebase } from 'angularfire2';

if (environment.production) {
  enableProdMode();
}

bootstrap(AppComponent, [
  FIREBASE_PROVIDERS,
  // Initialize Firebase app  - GET THIS ON https://console.firebase.google.com/project/
    defaultFirebase({
    apiKey: "<YOUR CODE HERE- GET THIS ON https://console.firebase.google.com/project/>",
    authDomain: "<YOUR CODE HERE- GET THIS ON https://console.firebase.google.com/project/>",
    databaseURL: "<YOUR CODE HERE- GET THIS ON https://console.firebase.google.com/project/>",
    storageBucket: "<YOUR CODE HERE- GET THIS ON https://console.firebase.google.com/project/>"
  })
]);
//end of main.ts

```

`ng serve`

Bye!
